apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-slow
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: www
          mountPath: /test-pd

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30003
  selector:
    app: nginx
  type: LoadBalancer

