apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: appjarcont
        image: pkajal/localhostimage:1.0 
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/ka_test
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: root
        ports:
        - containerPort: 4444

---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: NodePort
  selector:
    app: be
  ports:
    - protocol: TCP
      port: 4444
      nodePort: 30001
