--- 
apiVersion: v1
kind: Service
metadata: 
  name: mysql
spec: 
  type: NodePort
  ports: 
    - 
      name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30306
      protocol: TCP
  selector: 
    app: mysql
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
spec: 
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers: 
        - 
          env: 
            - 
              name: MYSQL_ROOT_PASSWORD
              value: root
            - 
              name: MYSQL_DATABASE
              value: ka_test
          image: "mysql:5.7"
          name: mysql
          ports: 
            - 
              containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /var/lib/mysql
              name: www
      volumes: 
        - 
          name: www
          persistentVolumeClaim: 
            claimName: pvc-nfs-pv1
