apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduit-frontend
  template:
    metadata:
      labels:
        app: conduit-frontend
    spec:
      containers:
        - image: rakeshkhot5/cond-f:2.0.0
          imagePullPolicy: Always
          name: conduit-frontend
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: conduit-fe-lb
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30308
  selector:
    app: conduit-frontend
